name: Build latest
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: build-latest
  cancel-in-progress: true

jobs:
  build-latest-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Pre-Release Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            - USER=ContainerAdministrator
          tags: ghcr.io/webbanditten/projector-rays-web:latest
