name: Build Images
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'feature/*'
      - 'fix/*'
      - 'master'
      - 'main'
jobs:
  build-pre-release-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Pre-Release Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/webbanditten/projector-rays-web:prerelease-${{ github.sha }}
      - name: Create Image Tag Comment
        if: ${{ success() }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (context.eventName !== 'pull_request') {
              console.log('Not a pull request event');
              return;
            }
            const imageTag = 'prerelease-' + '${{ github.sha }}';
            const commentBody = `The pre-release image can be pulled using: docker pull ghcr.io/webbanditten/projector-rays-web:${imageTag}`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody
            });
